- api/mod.go
- cmd/wavelet/main.go
- go.mod
- go.sum
- graph.go
- index.go
- ledger.go
- store/leveldb.go
graph, ledger, index: index completed transactions by their ids concurrently, create a Find() method that searches through both AVL tree and trie indices for account/smart contract/transaction ids
ledger, api: rename and document send quota token bucket-related methods for rate limiting a nodes ability to create transactions
store, cmd/wavelet: make wavelet by default use leveldbs in-memory database rather than an in-memory skiplist as a database
mod: add dependency on github.com/dghubble/trie
> Implement all that is necessary to enable autocomplete for CLI input across ledger data.

- cmd/graph/main.go
The bug is that the bootstrap peers flag arguments skip the first peer argument. It should start with 0 instead of 1.
> Fix a minor bug in cmd/graph flag arguments.

- ledger.go
This affects wavelet-client and Lens which are listening for "rejected" when Wavelet was sending out  "failed" events.
> Fix logged event type for rejected transactions.

- avl/tree.go
- avl/tree_test.go
This fixes a bug where if all of the tree nodes are removed (causing `root` to be `nil`), the changes will not be committed.
> Fix committing an AVL tree with a nil root.

- gossip.go
- ledger.go
- snowball.go
- sys/const.go
- utils.go
- vote.go
Stop pulling missing transactions in case state sync needs to be done immediately instead of waiting for now more missing transaction
Lower most of syncing related timeouts - pulling, querying etc
Add check for live connections in most places - before pulling and for `SelectPeers`
Change how gossip network part works - do not store streams, create new stream each time instead and just pass in case of error - it avoid problem using "dead" connection and connection which were not removed from map. And since we send transactions in batch overhead of creating new connection is not that big.
> Ledger state syncing / pull missing transactions - minor cleanup and improvements.

- api/mod.go
- cmd/wavelet/shell.go
- collapse.go
- genesis.go
- gossip.go
- graph.go
- graph_test.go
- ledger.go
- round.go
- rounds_test.go
- snowball.go
- sys/const.go
- tx.go
- tx_applier_test.go
- tx_json_test.go
api, cmd/wavelet, gossip, collapse, genesis, ledger, round: revert to original memory alloc model such that values are emphasized over pointers to ensure correctness
tx: fix AttachSenderToTransaction to properly sort and index parent seeds with respect to index locations of parent ids
tests: parallelize tests where possible
> Prefer values over heap-allocated values, simplify memory model, and fix appending parent transaction seeds to transactions.

- graph.go
- graph_test.go
`Graph.validateTransaction` accidentally skips checking if `ParentIDs[0]` is a duplicate transaction, or the transaction itself.
> graph: fix validateTransaction skipping a parent

- store/inmem.go
- utils_test.go
The test is suspected to fail intermittently because sometimes when some of the nodes are closed, `grpc.Client` doesn't have time to update its internal state to reflect the closed connection. This affects the outcome of the test as it depends on `client.GetState()`.
> utils: fix failing TestSelectPeers

- cmd/wavelet/actions.go
Fix a copy-paste error causing panic due to index out of range error.
> cmd/wavelet: fix panic when placing stake

- site/website/pages/en/index.js
Added a link to the AssemblyScript smart contract SDK github repo (https://github.com/perlin-network/smart-contract-as) to the SDK section of the site index page.
> docs: add link to AssemblyScript smart contract SDK to index page

- site/docs/api.md
Before, `/account/:id` according to the docs would return a 404 endpoint. This fixes the docs to have `/accounts/:id` which is the correct route.
> Fixed /accounts not plural.

- site/docs/smart-contracts.md
Currently the example uses the old `smart-contracts` crate and therefore doesn't work. This should fix it
> fix: update example contract docs

- site/docs/smart-contracts.md
Add a section on how to set the Nightly channel as the default channel for Rust.
> site: add command to set nightly as default channel

- cmd/wavelet/cli.go
- cmd/wavelet/main.go
- cmd/wavelet/main_test.go
- go.mod
- go.sum
- testutil.go
If `--wallet` is not specified when running `wavelet`, it is supposed to generate a random wallet. Currently, it will use `wallet/config.txt` by default.
Other than that, this PR adds tests for `cmd/wavelet`.
TODO:
> cmd/wavelet: fix unspecified flag not generating random wallet

- recovery.go
When the stall detector detects excessive memory usage, also write a binary heap dump
> resolver: write heap pprof to disk upon oom

- common.go
- contract.go
Bytes comparison in plain loop was inefficient and redundant.
> Optimize saving memory of contract snapshot.

- ledger_test.go
- testutil.go
> Add tests for ledger

- api/msg.go
- contract_test.go
- ledger.go
- ledger_test.go
- round.go
- tx_applier_test.go
api, ledger, round, tests: compute the difficulty factor based on the total number of applied/rejected transactions in a round
round: reduce transaction count to uint32 to prevent sending out 4 extra bytes per round
> Make the computation of a rounds difficulty factor more robust to attacks by adversaries, and reduce round binary size.

- ledger.go
The panic is caused by a single character mistake in ledger.SyncToLatestRound()
The mistake cause a new variable to be created instead of updating the existing variable.
> Fix a panic (send on closed channel) in SyncToLatestRound

- api/mod.go
- cmd/wavelet/main.go
- go.mod
- go.sum
Implement HTTPS API server using Let's Encrypt.
Add new flag `-api.host` which is the domain. 
To enable HTTPS, pass the flag `-api.host`, and also `api.port`.
The `api.port` is used to start a HTTP server to handle Let's Encrypt auth callbacks, and redirect all  HTTP traffic into HTTPS.
> Add support to enable HTTPS on the API server

- collapse_test.go
Add collapseTransactions benchmarks for all of the transaction types.
I did not add a benchmark for 100,000 contract creation transactions because it'll take too long to run.
Result of running the benchmark `go test -run=XXX -bench BenchmarkCollapseTransactions`:
```
goos: darwin
goarch: amd64
pkg: github.com/perlin-network/wavelet
BenchmarkCollapseTransactionsStake100-8                 	    2000	    988547 ns/op	  525740 B/op	    5661 allocs/op
BenchmarkCollapseTransactionsStake1000-8                	     100	  12907349 ns/op	 6339847 B/op	   71088 allocs/op
BenchmarkCollapseTransactionsStake10000-8               	      10	 142591827 ns/op	66430399 B/op	  755910 allocs/op
BenchmarkCollapseTransactionsStake100000-8              	       1	1598800887 ns/op	664925168 B/op	 7613962 allocs/op …
```
> Add collapseTransactions benchmarks

- ledger_test.go
- testutil.go
Some fixes:
- `WaitUntilConsensus` is introduced (probably need a better name, or complete refactor). `WaitForConsensus` waits for 3 seconds for a consensus round. If no consensus happens, it returns false, and it returns true if otherwise. `WaitUntilConsensus` waits up to 30 seconds for a consensus round, and simply fails the test if no consensus happens.
- Use `testnet.WaitForRound` instead of `testnet.WaitForConsensus`. The former should always be used to wait for a node to catch up to another node.
- `WaitUntilBalance` is introduced. It's not accurate to check the round index to ensure that the state has been updated, as it might take some time between `rounds.Save` and `accounts.Commit`. Happened to me a few times locally, where the balance did not match even though the round index …
> Fix failing tests

- cmd/wavelet/main.go
- cmd/wavelet/main_test.go
- collapse.go
- ledger.go
- log/mod.go
- protocol.go
- snowball.go
Refer to #212. This PR adds `-loglevel` cli param, which overrides the log level for all loggers in the `log` package.
> Allow setting log level via cli parameters

- cmd/wavelet/actions.go
- cmd/wavelet/cli.go
- cmd/wavelet/main_test.go
- conf/conf.go
- ledger.go
This PR adds the following config:
- `downloadTxTimeout`: used by `DownloadTx` and `DownloadMissingTx` RPC calls
- `checkOutOfSyncTimeout`: used by `CheckOutOfSync` RPC call
> Remove hardcoded timeout values

- graph.go
- graph_test.go
- ledger.go
- ledger_test.go
- store/testutil.go
- testutil.go
If a transaction depth is too low due to pruning, the transaction is now ignored.
> Ignore tx error caused by adding transactions with too low depth

- cmd/wavelet/main.go
Currently sync responses are limited to 4MB.  Under extreme conditions the responses may be larger.  Extend the buffer size to accommodate these cases.
> Use larger buffers for gRPC, to accomodate larger syncs

- cmd/wavelet/main.go
Make the error returned by `keys()` more debuggable by wrapping the errors instead of returning new errors.
> Improve error message of cmd/wavelet

- cmd/wavelet/main.go
Set the genesis data earlier in the startup to ensure it does not affect any testing
> Set the genesis data earlier in the startup

- cmd/wavelet/actions.go
- cmd/wavelet/main.go
- collapse.go
- collapse_test.go
- ledger.go
- sys/const.go
- tx.go
#232 #233 
Also changed naming for `collapse_test`
> Change transaction fee and reward calculations.

- ledger.go
When broadcasting nops, it is not beneficial to wait less than 100ms before retrying since there is a check to ensure that nops are not emitted faster than that
Also wait a bit between attempts to connect to all peers
> Improve delays

- ledger.go
ClosestPeers() tries to connect to all the peers, if they are down then this takes a long time.  ClosestPeerIDs() just returns the count of items in the table
> Speed up finding number of peers

- cmd/wavelet/main_test.go
There are couple of issues with the mockStdout in `main_test.go` which was triggered in the PR #256 .
- The buffer size of channel in the mockStdout is not big enough. If the logger writes more than the buffer, this'll block the logger.
- There's a possible crash in the mockStdout.
The crash log:
```
goroutine 812 [running]:
github.com/perlin-network/wavelet/cmd/wavelet.(*mockStdout).Write(0xc0002faae0, 0xc0002ae2a0, 0x57, 0x64, 0x26, 0xc0016d61b0, 0xc0000336c0)
/Users/ahmadmuzakkir/Documents/rkeene/wavelet/cmd/wavelet/main_test.go:542 +0x3d2
github.com/benpye/readline.(*wrapWriter).Write(0xc0002a4100, 0xc0002ae2a0, 0x57, 0x64, 0x0, 0x6000107, 0x0)
/Users/ahmadmuzakkir/go/pkg/mod/github.com/benpye/readline@v0.0.0-20181117181432-5ff4ccac79cf/operation.go:49 +0x194 …
```
> Fix the tests in main_test.go

- cmd/wavelet/main.go
- collapse.go
- collapse_test.go
- contract.go
- contract_test.go
- tx_applier.go
- tx_applier_test.go
tx/applier, contract, collapse, cmd/wavelet: speed up collapsetransactions by having reads/writes occur in-memory vs against the avl tree
> Speed up CollapseTransactions() by buffering changes to a map.

- avl/node.go
- avl/node_test.go
- db.go
- db_test.go
From the collapseTransactions benchmarks, I notice some slice allocations that can be reduced and the cost of defer() in node.go.
By improving the slice allocations and remove the use defer() in node.rehashNoWrite(), I saw there are some performance improvements, albeit minor in some cases.
Following are the statistics of the benchmarks. 
The benchmarks are ran 100 times.
<br />
Remove defer() in node.rehashNoWrite()
```
name             old time/op    new time/op    delta
RehashNoWrite-8     151ns ± 6%     120ns ± 5%  -20.39%  (p=0.000 n=96+95)
```
<br />
Preallocate the slices
<br />
```
name                 old time/op    new time/op    delta
ReadUnderAccounts-8    77.4ns ± 7%    42.4ns ± 8%  -45.24%  (p=0.000 n=86+98)
name                 old alloc/op   new alloc/op   delta …
```
> Some micro optimizations in db.go and node.go

- accounts.go
- api/mod.go
- cmd/wavelet/cli.go
- cmd/wavelet/main.go
- cmd/wavelet/main_test.go
- ledger.go
- log/mod.go
- recovery.go
- testutil.go
Refer to #181. Having proper cleanup will make our tests more robust, as currently tests may sometimes fail as it's possible for different instances of `Ledger` to interact with each other between tests. This usually happens with tests in `cmd/wavelet` package.
Things to do when stopping wavelet:
- [cli] Stop API server
- [cli] Stop GRPC (close all client connections, and then the server)
- [ledger] Stop all consensus-related goroutines
- [ledger] Stop GC goroutine (if enabled)
- [ledger] Stop stall detector goroutine
- [ledger] Wait for all of the goroutines above to complete
- [cli] Close KV
TODO:
> Cleanup ledger.

- ledger.go
Minor bug introduced in #244 where the ledger sync channel would be explicitly closed, even if it is not open.
> Only close the sync channel if it is open

- api/mod.go
- cmd/wavelet/actions.go
- collapse.go
- ledger.go
- mempool.go
- protocol.go
- transactions.go
Currently, the ledger's transactions are stored in the `Mempool` type. This can cause confusions because the content of transactions and mempool is different. The transactions contains finalized + pending transactions while mempool contains only pending transactions
This PR creates a `Transactions` type to store the transactions and make it a field in`Ledger` instead in `Mempool`. 
This will make it more flexible. In the future if we want to change how `transactions` are stored or to implement pruning.
> [himitsu] Refactor transactions in Mempool

- cmd/wavelet/main.go
- cmd/wavelet/update.go
- cmd/wavelet/update_unix.go
- cmd/wavelet/update_windows.go
- recovery_unix.go
- scripts/helper.sh
- sys/version.go
This PR improves Windows support concerning two areas:
1. Fixes build-constraints so that the software actually builds on Windows;
2. Partially addresses auto-update (see comments on whether or not the process exits)
> Improve Windows Support

- ledger.go
When client.PullTransactions() fails, nil gets subsequently dereferenced
```
5:10PM ERR failed to download missing transactions error: "rpc error: code = Unavailable desc = transport is closing" event: pull-transactions
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa76589]
goroutine 12 [running]:
github.com/perlin-network/wavelet.(*Ledger).PullTransactions(0xc0000c4460)
/home/rkeene/devel/perlin-dev/wavelet/ledger.go:448 +0x309
created by github.com/perlin-network/wavelet.(*Ledger).PerformConsensus
/home/rkeene/devel/perlin-dev/wavelet/ledger.go:351 +0x3f
exit status 2
```
```
...
416                                                 responseChan <- nil
...
447                 for _, res := range …
```
> Minor fix for a panic on failed pulls

- transactions.go
transactions: implement a missing transactions index, which indexes ids of transactions that need to be pulled from a nodes peers
transactions: implement MarkMissing(), BatchMarkMissing(), MissingIDs() which returns ids of transactions that are missing
transactions: document MarkMissing(), MissingIDs(), and ProposableIDs()
> Mark missing transactions.

- ledger.go
- transactions.go
ledger, transactions: have tx manager keep track of the latest block height, and only keep ids of missing transactions for at most PruningLimit finalized blocks
> Have missing transaction IDs expire over time.

- api/msg.go
- cmd/wavelet/actions.go
- transactions.go
- wctl/ledger.go
api, wctl, actions: provide info about what block proposal nodes prefer
transactions: only propose transactions that are suitable for the current block height
`num_tx` in LedgerStatus is the number of transactions in the mempool, and `num_tx_in_store` is the total number of transactions archived by a node.
> Add more debug info into cmd/wavelet, and make what transactions are proposed into a block more strict.

- transactions.go
- tx.go
- wctl/tx.go
transactions: delete pruned transactions in the for loop over buffer instead of in amidst iterating over mempool index, and add debug log
wctl: make sure block height assigned to transaction is the latest block height, not the next block height
tx: simplify NewTransaction() to use NewSignedTransaction()
> Minor cleanup over transactions, and fix off-by-one error in wctl.

- api/msg.go
- cmd/wavelet/actions.go
- ledger.go
- transactions.go
- transactions_test.go
- wctl/ledger.go
api, actions, wctl: add num_missing_tx to ledger status response and cli
ledger, transactions: have MarkMissing be an atomic operation that returns true if the transaction has been successfully marked missing
transactions: remove BatchMarkMissing as we do not use it
> Add num_missing_tx, and have MarkMissing be an atomic CAS operation.

- snowball.go
- snowball_test.go
- vote.go
Currently, snowball.Tick() has weird and redundant parameters `(tallies map[VoteID]float64, votes map[VoteID]Vote)`.
This PR refactors vote.go and snowball.go to include the tally in the `Vote`, so the snowball.Tick() has single parameter `(votes []Vote)`.
This PR also adds unit tests for `snowball.go`.
> Refactor Snowball and add unit tests

- api/mod.go
- cmd/wavelet/node/node.go
Currently the callbacks for peers joining/leaving are set after the node starts listening for peers.  This creates a data race where `connLoop()` in Noise attempts to call those callbacks while the Wavelet node is registering them.
There is a separate PR ( https://github.com/perlin-network/noise/pull/254 ) to ensure that this does not cause a race condition, but it may be a good idea to ensure that these callbacks are registered before listening for connections.
> Ensure that callbacks are registered before listening

- block.go
- conf/conf_test.go
- ledger.go
Since previously block id contained merkle root it changed depending on collapse result. Which led to double collapse call and wrong merkle for smart contracts.
> Change block id to consist of transaction ids.

- .github/workflows/workflow.yml
- ledger_test.go
- testutil.go
- tx_applier_test.go
This PR re-adds the following tests that have been commented out to speed up implementation of himitsu:
Make sure PR #315 is merged first before merging this PR.
> Add wavelet tests

- conf/conf.go
- transactions.go
In order to not get block so big, that it will be impossible to send it over grpc, add limit to transactions number within the block.
> Limit transactions within the block.

- vote_test.go
Add more unit tests to increase coverage to 100% for both `vote.go` and `snowball.go`.
> Improve the vote unit tests coverage

- block.go
It was my mistake to use bytebuffer in the first place, since we leak slice from marshaling call, which makes access to same slice (same buffer) from different places.
Ideally we should put buffer back after we done with marshalled block, but we do not know where exactly it happens.
This caused a lot of race condition warnings
> Revert "block: use buffer pool for marshaling block (#322)"

- wctl/tx_find.go
The bug is because, for Contract, we use the Transaction ID as its ID.
So, we need to check for account first, before transaction.
> WCTL: Fix Find method returned a Transaction when the ID is actually a Contract

- wctl/tx_pay.go
Current the IsContract condition, is using the client account.
It should be using the recipient account.
> WCTL: fix pay to contract where the contract parameters are not set.

- cmd/wavelet/node/node.go
- store/inmem.go
Currently, in case of the database directory is empty, we will use the LevelDB's In-Memory storage.
We have our own In-Memory KV implementation, and by using LevelDb's In-Memory storage, it makes it harder to change database.
I guess the main reason we don't use own In-Memory KV, is because it does not work because of bugs.
This PR fixes the In-Memory KV bugs and use it in case when database directory is empty.
> Use In-Memory KV database

- cmd/wavelet/events.go
While investigating problem with connect-disconnect test being stuck, I found that cleanup functions slice is passed as value and then modified by append, which result in new slice creation and none of the cleanup functions actually being applied.
Not the best fix, I personally don't like slices being appended like that, but its easiest one with no changes to current approach.
> Fix cli cleanup funcs slice being not modified.

- cmd/wavelet/events.go
- ledger.go
- tx_applier.go
- wctl/tx.go
- wctl/ws_callbacks.go
- wctl/ws_tx.go
This PR enables collapseTransactions log. For some reason it's disabled.
Also, this PR fixes a potential panic in collapseTransactions and removes unused fields in wctl.
> Enable collapseTransactions log

- .github/workflows/workflow.yml
In PR #332, I separate tests into 2 runs: 1 for unit tests, and 1 for integration tests. The second test run currently overwrites the coverage report from the first test run. This PR merges the 2 coverage results instead.
> Merge coverage result from multiple test runs

- api/mod_ws_integration_test.go
- cmd/wavelet/events.go
- collapse.go
- ledger.go
- testutil.go
- wctl/wctl.go
- wctl/ws_accounts.go
- wctl/ws_callbacks.go
This PR adds `nonce_updated` under `accounts` log module, which the client can use to get the updated nonce for an account.
> Add nonce_updated event

- api/mod.go
- api/mod_ws_integration_test.go
- cmd/wavelet/main.go
- genesis_integration_test.go
- ledger.go
- log.go
- log/io.go
- log/mod.go
- log_test.go
- snowball_test.go
There's a serious performance issue on the logging of collapse results. 
This performance issue can be severe when there are more than 10,000 transactions in a block. And it can have cascading impact on the performance of finalization (at least on my machine).
As you can see below, it can take more than 1 second to log a collapse result.
(The number in brackets is the number of transactions)
```
»»» logging collapse results (3946) took 76.556821ms
»»» logging collapse results (24215) took 472.709766ms
»»» logging collapse results (3927) took 69.653531ms
»»» logging collapse results (20420) took 470.434397ms
»»» logging collapse results (8291) took 177.229131ms
»»» logging collapse results (26042) took 503.408222ms
»»» logging collapse results (22277) took 455.032903ms
»»» logging collapse …
```
> Optimize logging collapse results

- accounts_test.go
- ledger_integration_test.go
- testutil.go
This is a WIP PR that contains improvements and some experiments to improve testing on the CI.
- `WaitUntilConsensus` sometimes times out, especially if you run the tests locally. My guess is this happens when the test environment is too fast, and one consensus block managed to happen before the call to `WaitUntilConsensus`. Instead, use `WaitUntilBlock` and explicitly specify the block index the test is waiting for.
- Remove all timeouts from test methods. Global test timeout is used instead.
> Test improvements and experiments.

- cmd/wavelet/main.go
Use a separate flag to specify the host wctl should connect to versus… the one we want to allow for HTTPS API access
> Separate usage of the "api.host" flag

- cmd/wavelet/cli.go
Dump command appears twice under `help`. And because it has no alias, it looks weird with empty bracket:
> Remove duplicated dump entry in help, and add alias

- .github/workflows/workflow.yml
Few improvements to speed up CI cycle:
> Github CI improvements.

- .github/workflows/workflow.yml
- genesis_integration_test.go
The tests are flaky because it does not properly wait for all nodes to sync, and uses `WaitUntilConsensus` instead of `WaitUntilBlock`.
> Fix failing genesis tests

- ledger.go
- lru.peerblock.go
This PR will clear the `queryPeerBlockCache` when a block is finalized, since the cache is only valid for a block.
> Keep peer block query responses in bounded LRU cache.

- vote.go
Fixes consistency on consensus/issues with stalling.
> vote: normalize individual weights before passing through Normalize()

- tx_validate.go
- tx_validate_test.go
This PR fixes a bug with batch transaction validation.
The bug is that we verify the transactions in a batch. We're only supposed to verify the signature of the batch transaction.
https://trello.com/c/iSNno8Fi/108-fix-benchmarking-broken-because-of-prevalidation-of-transactions
> Fix batch transaction signature validation

- Dockerfile
- Makefile
Currently, the wavelet stack is not guaranteed to deploy the latest image if it is not explicitly tagged. This adds the git commit ref to the docker image, so that we can easily check it in the ctl and ensure that the expected build is deployed.
> fix(Docker): Add git version to docker build

- api/mod.go
- api/ws.go
- collapse.go
- ledger.go
- wctl/ws.go
- wctl/ws_accounts.go
1. There were arena allocations that were not being cleaned up which sprung up a memory leak. That got fixed.
2. Stale logs are being debounced to the websocket. Temporarily disable debouncing for the time being in the HTTP API.
3. To prevent ourselves from hitting the database too much, print out changes in state from a CollapseContext instance.
api, wctl: fix memory leak over json parser not being returned to pool
api, ws, wctl: tmp remove debouncing because of stale messages being pushed to websocket
ledger: make LogChanges log changes from a collapse context rather than from the avl tree
> Fix memory leak in arena allocation in API, temporarily remove API message debouncing, and speed up logging state changes.

- log/console.go
This PR adds second to log timestamp format to make it easier to debug.
> Add second to log timestamp format

- cmd/wavelet/cli.go
- cmd/wavelet/main.go
- log/console.go
This is added to assist debugging, because piping the output of the log with colors makes it slightly unreadable due to the presence of control characters on some text editors.
> Add log.nocolor flag to disable color in logs
