tx_parser_test.go

Add tests for `Parse*Transaction` functions.

tx_parser: add tests

---

avl/tree_test.go
store/testutil.go
utils_test.go

Added `TestSelectPeers`. Also added test utility `newNode`, which might be useful for other tests.

utils: add test for SelectPeers

---

contract.go

TODO:
Let the transaction sender pay for the gas fee of calling the start function?

Call the start function of a smart contract (if exists) at initialization.

---

collapse.go
contract.go
contract_test.go
tx_applier.go
tx_applier_test.go

Add per-round caching for smart contract state.

---

site/docs/examples/decentralized-chat-app.md
site/docs/examples/decentralized-todo-app.md
site/website/sidebars.json

Created additional section for tutorials. 
Content is not identical to the original medium articles. They have been appropriated for the docs website.

docs: add markdown for tutorials on building decentralised applications on Wavelet

---

graph.go

graph: reorganize where autocompletion indexing takes place; prior to the reorganization there existed a memory leak in the autocompletion trie

Fix memory leak in autocompletion trie.

---

site/docs/examples/decentralized-todo-app.md

Now the code does not compile. It compiles when i change all the return type from -> Result<(), Box<dyn Error>> to -> Result<(), String>

Keep example updated: change result type

---

site/docs/smart-contracts.md

Updated docs to align with the change "Separate contract invocation parameters to a new type." https://github.com/perlin-network/smart-contract-rs/commit/aca6d287f374a579acb1d1d95fbac1f86d464b0c

docs: fixed a compilation error in the code snippet

---

Makefile

This will make it easier to specify the registry and tag.

Improve Docker build support within the Makefile.

---

accounts.go
api/middleware.go
api/mod.go
api/mod_test.go
api/mod_ws_test.go
api/msg.go
cmd/graph/main.go
cmd/wavelet/actions.go
cmd/wavelet/cli.go
cmd/wavelet/main.go
conf/conf.go
ledger.go
recovery.go
store/inmem.go
store/leveldb.go
store/mod.go
sys/const.go
testutil.go

Add api endpoint for connecting disconnecting node.

---

cmd/wavelet/main.go
cmd/wavelet/update.go
cmd/wavelet/update_unix.go
cmd/wavelet/update_windows.go
scripts/helper.sh
sys/version.go

For the current testnet release, we want to be able to fix bugs as they arise.  To facilitate this we will enable an auto-updater.

Add auto-updater

---

cmd/wavelet/main_test.go
ledger.go

When dealing with a captured value which is a pointer we want to make sure we are dealing with the iterated value rather than the last one

Fix captured value

---

api/mod_test.go
go.mod
go.sum
ledger.go

This includes perlin-network/noise#242 which addresses issues with invalid peers

Upgrade to the latest commit of Noise

---

conf/conf.go

Large downloads can take a while, set better defaults

Increase timeouts again

---

conf/conf.go
scripts/helper.sh
sys/const.go
sys/version.go

There needs to be a consolidated place to put this information in the future

Set defaults based on network

---

cmd/benchmark/main.go
cmd/wavelet/main.go
wctl/tx.go
wctl/wctl.go
wctl/ws.go
wctl/ws_consensus.go

This is the continuation of PR #292.

Properly increment nonce and block height in wctl client

---

ledger.go

There were 2 returns with no writes to `voteChan`, but we expected to have fixed number of values in that channel. So in case number was less than expected query process would stuck indefinitely waiting to read from channel.
+ simplify concurrency

Fix concurrency bug in querying if request have failed.

---

ledger.go
transactions.go

Add BatchMarkMissing

---

api/mod.go
cmd/wavelet/cli.go
conf/conf.go
ledger.go
recovery.go
tx_applier.go

- simplify concurrency for querying
- add channel read timeout for voting results
- change shutdown for stall detector
- minor style fixes

Shutdown investigation results.

---

ledger.go

Detected in PR #314 while running tests. Originally part of that PR, but it's better to have a separate PR for fixing it.

Fix race conditions

---

api/msg.go

This PR fixes a bug in "preferred" object response of ledgerStatusResponse.

Fix Ledger Status API response

---

cmd/wavelet/node/node.go
testutil.go

Tests were failing due to out of memory errors

Continue to use LevelDB until BadgerDB is sorted out

---

api/mod.go
ledger.go
transactions.go
tx.go

This PR makes the callers BatchAdd() and Add() perform the signature verification.
This is to avoid the mutex from being held for too long.

Improve signature verification

---

debounce/debounce_test.go

All debounce tests now indefinitely wait for `done` channel to be closed in order to check if the test succeeds.

Fix flaky debounce tests.

---

api/mod_integration_test.go
api/mod_ws_integration_test.go
cmd/wavelet/node/node.go
ledger.go
testutil.go
utils_test.go

Add error as return value and handle it on upper level

Have NewLedger return errors.

---

blocks_test.go

Add blocks tests.

---

ledger.go
protocol.go
tx_validate.go

#417 
All explanation will be in issue description.

Fix syncing contract transaction.

---

dbg.go
dbg_noop.go
ledger.go
snowball.go

ledger: force nodes to sample themselves
ledger, snowball, dbg: add printf logs enabled via build tags for debugging consensus-related issues

ledger: force nodes to sample themselves

---

ledger.go

Small simplification for query results cache.

Remove unnecessary fields from query results.
